[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_CALENDLY_URL = "https://calendly.com/osayeedjaber18"
  NEXT_PUBLIC_DISCORD_WEBHOOK_URL = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TOML_ENV = "production"
  NODE_ENV = "production"
